version: "2"
services:
  amidown:
    image: shukriadams/amidown:latest
    container_name: amidown
    restart: unless-stopped
    environment:
      verbose : 'true'
    volumes:
      - ./settings.json:/var/app/settings.json
      - ./flags:/var/app/flags/:rw
      - ./logs:/var/app/__logs/:rw
    ports:
    - "7018:3018"
