smtp:
    enabled: false
    server : my.server
    port : 25,
    secure : false
    from : no-reply@example.com

slack:
    enabled: false
    something: 123
    someotherthing: abc

recipients :
    me:
        enabled: false
        email:  me@example.com
        slack : slackid
    bob:
        email : bob@example.com

watchers:
    manafeed:
        interval: "*/35 * * * * *"
        url: http://manafeed.com/
    first:
        interval: "*/5 * * * * *" 
        name: first thing # this is optional
        url: http://thing.example.com/
        test: user/example
        recipients :  me,bob #override
    second: 
        url : http://second.example.com/
        enabled: false
    third:
        test: mytest
        some_arg : whatever

dashboards:
    mydash:
        name : stuff to watch
        watchers: first, third
