dashboardRefreshInterval: 5000

smtp:
    enabled: false
    server : my.server
    port : 25,
    secure : false
    from : no-reply@example.com

slack:
    enabled: false
    something: 123
    someotherthing: abc

recipients :
    me:
        enabled: false
        email:  me@example.com
        slack : myslackid
    bob:
        email : bob@example.com

watchers:
    example:
        interval: "*/2 * * * *"
        url: http://example.com
    another:
        interval: "1 * * * *" 
        # name is optional, node name "another" will be used as fallback
        name: first thing 
        url: http://example.com
        # call this script to perform up test 
        test: user/example
        recipients :  me,bob 

dashboards:
    all:
        # name is optional, node name "all" will be use as fallback
        name : All the things
        watchers: example, another
    single:
        watchers: example
