name: builds docker images
on: 
  push:
    tags:
      - '*'

jobs:

    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: run code tests and ensure 100% test coverage
          run: cd build && sh ./test-preRelease.sh
          env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
    
    docker-arm7:
        runs-on: self-hosted
        steps:
        # clean before building    
        - name: cleanup
          run: |
            echo "Cleaning up previous run"
            sudo rm -rf "${{ github.workspace }}"
        - uses: actions/checkout@v1
        - name: builds armv7 container and pushes to docker hub
          run:  cd build && sh ./build-dockerImage.sh --dockerpush --smoketest --arch arm32v7
          env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}

    docker-amd64:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: builds amd64 container and pushes to docker hub
          run:  cd build && sh ./build-dockerImage.sh --dockerpush --smoketest --arch amd64
          env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}

    wait:    
        - name: Wait 20 seconds so last container image has a chance to upload
          run: sleep 20s
          shell: bash

    manifest:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: builds manifest
          run:  cd build && sh ./build-dockerManifest.sh
          env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}            