name: builds all the things
on: 
  push:
    tags:
      - '*'
jobs:
    buildArm:
        runs-on: self-hosted
        steps:
        # clean before building    
        - name: cleanup
          run: |
            echo "Cleaning up previous run"
            sudo rm -rf "${{ github.workspace }}"
        - uses: actions/checkout@v1
        - name: builds docker container and pushes to docker hub
          run:  cd build && sudo sh ./build.sh --dockerpush --smoketest --arc -arm
          env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
        

    buildx86:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: builds docker container and pushes to docker hub
          run:  cd build && sh ./build.sh --dockerpush --smoketest
          env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}